spring.application.name=gestionpedidos

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_pedidos
spring.datasource.username=postgres
spring.datasource.password=P1tr3c31$

# Estrategia de creación de tablas en desarrollo
spring.jpa.hibernate.ddl-auto=update

# Mostrar y formatear las consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
